Repository nuxt/nuxtjs.org, pull requests merged in 2020-12, with the labels that each got.

#1054 docs(ja): translate pages-middleware
  content/ja/guides/components-glossary/pages-middleware.md
Labels: japanese

#1044 docs(ja): translate configuration-servermiddleware
  content/ja/guides/configuration-glossary/configuration-servermiddleware.md
Labels: japanese

#1069 docs(ja): Minute changes (ja translation) in env property
  content/ja/guides/configuration-glossary/configuration-env.md
Labels: japanese

#1055 docs(ja): translate directory-structure/static
  content/ja/guides/directory-structure/static.md
Labels: japanese

#1075 Docs/french translation
  content/fr/guides/components-glossary/pages-fetch.md
  content/fr/guides/components-glossary/pages-head.md
  content/fr/guides/components-glossary/pages-key.md
  content/fr/guides/components-glossary/pages-layout.md
  content/fr/guides/components-glossary/pages-loading.md
  content/fr/guides/components-glossary/pages-middleware.md
  content/fr/guides/components-glossary/pages-scrolltotop.md
  content/fr/guides/components-glossary/pages-transition.md
  content/fr/guides/components-glossary/pages-validate.md
  content/fr/guides/components-glossary/pages-watchquery.md
  content/fr/guides/concepts/context-helpers.md
  content/fr/guides/concepts/nuxt-lifecycle.md
  content/fr/guides/concepts/views.md
  content/fr/guides/configuration-glossary/configuration-build.md
  content/fr/guides/features/data-fetching.md
  content/fr/guides/features/rendering-modes.md
  content/fr/guides/get-started/commands.md
  content/fr/guides/get-started/installation.md
  content/fr/guides/internals-glossary/context.md
  content/fr/guides/internals-glossary/internals-builder.md
  content/fr/guides/internals-glossary/internals-generator.md
  content/fr/guides/internals-glossary/internals-module-container.md
  content/fr/guides/internals-glossary/internals-renderer.md
  content/fr/guides/internals-glossary/internals.md
Labels: french

#1080 docs(ja): fix name of example to match with object listed above
  content/ja/guides/features/transitions.md
Labels: japanese

#1061 docs(id): translation directory-structure
  content/id/guides/directory-structure/content.md
Labels: indonesia

#898 docs(id): directory translation directory-structure
  content/id/guides/directory-structure/components.md
  content/id/guides/directory-structure/middleware.md
Labels: indonesia

#1076 docs(ja): translate configuration-telemetry
  content/ja/guides/configuration-glossary/configuration-telemetry.md
Labels: japanese

#1077 docs(ja): translate configuration-router
  content/ja/guides/configuration-glossary/configuration-router.md
Labels: japanese

#1110 fixed typo
  content/fr/guides/get-started/installation.md
Labels: french

#1114 docs(ja): fix missing back quote. `content/ja/guides/get-started/upgrading.md`
  content/ja/guides/get-started/upgrading.md
Labels: japanese

#1106 docs(ja): translate guides/features/rendering-modes.md
  content/ja/guides/features/rendering-modes.md
Labels: japanese
