Repository nuxt/nuxtjs.org, pull requests merged in 2020-10, with the labels that each got.

#693 docs(ja): translate guides/get-started/conclusion
  content/ja/guides/get-started/conclusion.md
Labels: japanese

#612 docs(ja): translate guides/get-started/routing
  content/ja/guides/get-started/routing.md
Labels: japanese

#666 docs(ja): translate guides/get-started/upgrading
  content/ja/guides/get-started/upgrading.md
Labels: japanese

#734 docs(ja): translate guides/configuration-glossary/configuration-css
  content/ja/guides/configuration-glossary/configuration-css.md
Labels: japanese

#733 docs(ja): translate guides/configuration-glossary/configuration-components
  content/ja/guides/configuration-glossary/configuration-components.md
Labels: japanese

#732 docs(ja): translate guides/configuration-glossary/configuration-cli
  content/ja/guides/configuration-glossary/configuration-cli.md
Labels: japanese

#731 docs(ja): translate guides/configuration-glossary/configuration-builddir
  content/ja/guides/configuration-glossary/configuration-builddir.md
Labels: japanese

#730 docs(ja): translate guides/configuration-glossary/configuration-build
  content/ja/guides/configuration-glossary/configuration-build.md
Labels: japanese

#667 docs(ja): translate guides/get-started/installation
  content/ja/guides/get-started/installation.md
Labels: japanese

#773 Russian translation: Get started
  content/ru/guides/get-started/conclusion.md
  content/ru/guides/get-started/directory-structure.md
  content/ru/guides/get-started/installation.md
  content/ru/guides/get-started/routing.md
  content/ru/guides/get-started/upgrading.md
  i18n/ru-RU.js
Labels: russian

#744 [Korean] translate configuration.md
  content/ko/guides/features/configuration.md
Labels: korean

#837 fix: improve get started
  content/en/guides/get-started/installation.md
Labels: docs

#843 docs(ja): translate guides/configuration-glossary/configuration-global-name
  content/ja/guides/configuration-glossary/configuration-global-name.md
Labels: japanese

#841 docs(ja): translate guides/configuration-glossary/configuration-ignore
  content/ja/guides/configuration-glossary/configuration-ignore.md
Labels: japanese

#794 docs(id): Translate id/guides/directory-structure/nuxt.md
  content/id/guides/directory-structure/nuxt.md
Labels: indonesian

#750 docs(ja): translate guides/features/loading
  content/ja/guides/features/loading.md
Labels: japanese

#714 docs(ja): translate guides/features/meta-tag-seo
  content/ja/guides/features/meta-tags-seo.md
Labels: japanese

#729 docs(ja): translate guides/get-started/directory-structure
  content/ja/guides/get-started/directory-structure.md
Labels: japanese

#754 [docs-id] Translation for guides/layouts.md
  content/id/guides/directory-structure/layouts.md
Labels: indonesian

#851 feat: improve redirect docs
  content/en/guides/concepts/context-helpers.md
  content/en/guides/internals-glossary/context.md
Labels: docs

#844 feat: add commands page
  components/partials/home/HomeModes.vue
  content/en/guides/configuration-glossary/configuration-generate.md
  content/en/guides/configuration-glossary/configuration-loading-indicator.md
  content/en/guides/configuration-glossary/configuration-modern.md
  content/en/guides/configuration-glossary/configuration-render.md
  content/en/guides/configuration-glossary/configuration-ssr.md
  content/en/guides/directory-structure/middleware.md
  content/en/guides/features/deployment-targets.md
  content/en/guides/features/loading.md
  content/en/guides/features/rendering-modes.md
  content/en/guides/get-started/commands.md
  i18n/en-US.js
  i18n/es-ES.js
  i18n/fa-IR.js
  i18n/fr-FR.js
  i18n/id-ID.js
  i18n/ja-JP.js
  i18n/ko-KO.js
  i18n/pt-BR.js
  i18n/ru-RU.js
  i18n/tr-TR.js
  i18n/zh-ZH.js
Labels: docs

#770 docs(ja): translate guides/features/nuxt-components
  content/ja/guides/features/nuxt-components.md
Labels: japanese

#755 docs(ja): translate guides/features/configuration
  content/ja/guides/features/configuration.md
Labels: japanese

#859 docs(ja): translate guides/configuration-glossary/configuration-modern
  content/ja/guides/configuration-glossary/configuration-modern.md
Labels: japanese

#842 docs(ja): translate guides/configuration-glossary/configuration-generate
  content/ja/guides/configuration-glossary/configuration-generate.md
Labels: japanese

#852 docs(id): improve i18n/id-ID.js
  i18n/id-ID.js
Labels: indonesian

#846 docs(id) : translate guides/configuration-glossary
  content/id/guides/configuration-glossary/configuration-components.md
  content/id/guides/configuration-glossary/configuration-dir.md
  content/id/guides/configuration-glossary/configuration-extend-plugins.md
Labels: indonesian

#765 docs(ja): translate guides/features/file-system-routing
  content/ja/guides/features/file-system-routing.md
Labels: japanese

#793 docs(id): fix type in faq/jsx.md and add files guides/internals-glossary v2
  content/id/faq/jsx.md
  content/id/guides/internals-glossary/nuxt-render-and-get-window.md
  content/id/guides/internals-glossary/nuxt-render-route.md
  content/id/guides/internals-glossary/nuxt-render.md
  content/id/guides/internals-glossary/nuxt.md
Labels: indonesian

#891 docs(ja): translate guides/features/data-fetching (re-create)
  content/ja/guides/features/data-fetching.md
Labels: japanese

#861 docs(ja): translate guides/configuration-glossary/configuration-indicator
  content/ja/guides/configuration-glossary/configuration-loading-indicator.md
Labels: japanese

#863 docs(ja): translate guides/configuration-glossary/configuration-hooks
  content/ja/guides/configuration-glossary/configuration-hooks.md
Labels: japanese

#895 docs(ja): translate config-glossary/config-modulesdir
  content/ja/guides/configuration-glossary/configuration-modulesdir.md
Labels: japanese

#896 docs(ja): translate config-glossary/config-plugins
  content/ja/guides/configuration-glossary/configuration-plugins.md
Labels: japanese

#862 docs(ja): translate guides/configuration-glossary/configuration-loading
  content/ja/guides/configuration-glossary/configuration-loading.md
Labels: japanese

#910 docs(es): Update spanish
  content/es/guides/concepts/context-helpers.md
  content/es/guides/concepts/nuxt-lifecycle.md
  content/es/guides/directory-structure/nuxt-config.md
  content/es/guides/directory-structure/plugins.md
Labels: spanish
