Repository nuxt/nuxtjs.org, pull requests merged in 2021-03, with the labels that each got.

#1266 docs(ja): translate directory-structure/plugins
  content/ja/guides/directory-structure/plugins.md
Labels: japanese

#1294 doca(ja): remove unwanted particles
  content/ja/guides/configuration-glossary/configuration-generate.md
Labels: japanese

#1303 docs(ja): documented new loadingSreen property
  content/ja/_archives/api/configuration-build.md
Labels: japanese

#1259 docs(ja): translate internals-glossary/internals-generator
  content/ja/guides/internals-glossary/internals-generator.md
Labels: japanese

#1260 docs(ja): translate internals-glossary/internals-module-container
  content/ja/guides/internals-glossary/internals-module-container.md
Labels: japanese

#1261 docs(ja): translate internals-glossary/internals-nuxt
  content/ja/guides/internals-glossary/internals-nuxt.md
Labels: japanese

#1296 docs(id): Translate configuration glossary
  content/id/guides/configuration-glossary/configuration-ignore.md
  content/id/guides/configuration-glossary/configuration-mode.md
  content/id/guides/configuration-glossary/configuration-plugins.md
  content/id/guides/configuration-glossary/configuration-rootdir.md
Labels: indonesia

#1314 docs(ja): Update configuration-hooks.md
  content/ja/guides/configuration-glossary/configuration-hooks.md
Labels: japanese

#1315 docs(ja): documented webpack config inspection
  content/ja/guides/get-started/commands.md
Labels: japanese

#1297 docs(id): Numerous translation fixes for homepage
  i18n/id-ID.js
Labels: indonesia

#1305 docs(ja): fix to add single quotes in directory-structure/plugins
  content/ja/guides/directory-structure/plugins.md
Labels: japanese

#1306 docs(ja): translate internals-glossary/nuxt-render-and-get-window
  content/ja/guides/internals-glossary/nuxt-render-and-get-window.md
Labels: japanese

#1307 docs(ja): translate internals-glossary/nuxt
  content/ja/guides/internals-glossary/nuxt.md
Labels: japanese

#1308 docs(ja): translate internals-glossary/nuxt-render
  content/ja/guides/internals-glossary/nuxt-render.md
Labels: japanese

#1309 docs(ja): translate internals-glossary/nuxt-render-route
  content/ja/guides/internals-glossary/nuxt-render-route.md
Labels: japanese

#1310 docs(ja): translate internals-glossary/internals-renderer
  content/ja/guides/internals-glossary/internals-renderer.md
Labels: japanese

#1322 docs(id): Translation from configuration-modern to configuration-modulesdir
  content/id/guides/configuration-glossary/configuration-modern.md
  content/id/guides/configuration-glossary/configuration-modules.md
  content/id/guides/configuration-glossary/configuration-modulesdir.md
Labels: indonesia

#1324 docs(id): Translate configuration-glossary
  content/id/guides/configuration-glossary/configuration-loading-indicator.md
  content/id/guides/configuration-glossary/configuration-loading.md
  content/id/guides/configuration-glossary/configuration-server.md
Labels: indonesia

#1326 docs(id): translation for configuration guides (runtime-config -> ssr)
  content/id/guides/configuration-glossary/configuration-runtime-config.md
  content/id/guides/configuration-glossary/configuration-ssr.md
Labels: indonesia

#1343 docs(fr): fix typo (imporant to important)
  content/fr/guides/concepts/views.md
Labels: french

#1327 docs(ja): document the unit for the `interval` property
  content/ja/guides/configuration-glossary/configuration-generate.md
Labels: japanese

#1328 docs(ja): Configuration glossary/configuration render
  content/ja/guides/configuration-glossary/configuration-render.md
Labels: japanese

#1329 docs(ja): update features/nuxt-components
  content/ja/guides/features/nuxt-components.md
Labels: japanese

#1330 docs(ja): update untranslated documents
  content/ja/guides/directory-structure/components.md
Labels: japanese

#1332 docs(ja): fix guides/features documents
  content/ja/guides/features/configuration.md
  content/ja/guides/features/data-fetching.md
  content/ja/guides/features/loading.md
  content/ja/guides/features/meta-tags-seo.md
  content/ja/guides/features/nuxt-components.md
  content/ja/guides/features/transitions.md
Labels: japanese

#1367 docs(ja): update some documents and move faq
  content/ja/_archives/faq/appengine-deployment.md
  content/ja/_archives/faq/async-data-components.md
  content/ja/_archives/faq/cached-components.md
  content/ja/_archives/faq/css-flash.md
  content/ja/_archives/faq/deployment-aws-s3-cloudfront.md
  content/ja/_archives/faq/deployment-azure-portal.md
  content/ja/_archives/faq/deployment-azure-static-web-apps.md
  content/ja/_archives/faq/dokku-deployment.md
  content/ja/_archives/faq/duplicated-meta-tags.md
  content/ja/_archives/faq/extend-webpack.md
  content/ja/_archives/faq/external-resources.md
  content/ja/_archives/faq/ga.md
  content/ja/_archives/faq/github-pages.md
  content/ja/_archives/faq/heroku-deployment.md
  content/ja/_archives/faq/host-port.md
  content/ja/_archives/faq/http-proxy.md
  content/ja/_archives/faq/ios-phone-numbers.md
  content/ja/_archives/faq/jsx.md
  content/ja/_archives/faq/netlify-deployment.md
  content/ja/_archives/faq/nginx-proxy.md
  content/ja/_archives/faq/postcss-plugins.md
  content/ja/_archives/faq/pre-processors.md
  content/ja/_archives/faq/surge-deployment.md
  content/ja/_archives/faq/using-nuxt-with-cloudflare.md
  content/ja/_archives/faq/vercel-deployment.md
  content/ja/_archives/faq/webpack-audio-files.md
  content/ja/_archives/faq/webpack-plugins.md
  content/ja/_archives/faq/window-document-undefined.md
  content/ja/guides/components-glossary/pages-head.md
  content/ja/guides/concepts/server-side-rendering.md
  content/ja/guides/configuration-glossary/configuration-css.md
  content/ja/guides/configuration-glossary/configuration-head.md
  content/ja/guides/directory-structure/assets.md
  content/ja/guides/directory-structure/nuxt-config.md
  content/ja/guides/features/configuration.md
  content/ja/guides/features/data-fetching.md
Labels: japanese
