Repository nuxt/nuxtjs.org, pull requests merged in 2021-07, with the labels that each got.

#1450 docs(ru): Features section
  content/ru/guides/features/configuration.md
  content/ru/guides/features/data-fetching.md
  content/ru/guides/features/file-system-routing.md
  content/ru/guides/features/loading.md
  content/ru/guides/features/meta-tags-seo.md
  content/ru/guides/features/nuxt-components.md
  content/ru/guides/features/transitions.md
Labels: russian

#1539 docs: remove english sentence on french module page
  content/fr/guides/directory-structure/modules.md
Labels: documentation, french

#1542 docs(fr): new version 3 translation
  content/fr/0.docs/8.deployment/1.21yunbox.md
  content/fr/0.docs/8.deployment/2.amazon-web-services.md
  content/fr/0.docs/8.deployment/22.vercel.md
  content/fr/0.docs/8.deployment/3.azure-portal.md
  content/fr/0.docs/8.deployment/4.azure-static-web-apps.md
  content/fr/0.docs/8.deployment/5.bip.md
  content/fr/0.docs/8.deployment/6.cleavr.md
  content/fr/0.docs/8.deployment/7.do-app-platform.md
  content/fr/1.examples/1.routing/1.hello-world.md
  content/fr/1.examples/1.routing/2.active-link-classes.md
  content/fr/1.examples/1.routing/3.dynamic-pages.md
  content/fr/1.examples/1.routing/4.nested-pages.md
  content/fr/1.examples/1.routing/index.md
  content/fr/1.examples/10.modules/1.local.md
  content/fr/1.examples/10.modules/2.axios.md
  content/fr/1.examples/2.data-fetching/1.async-data.md
  content/fr/1.examples/2.data-fetching/2.fetch-hook.md
  content/fr/1.examples/2.data-fetching/index.md
  content/fr/1.examples/3.assets-management/1.pre-processors.md
  content/fr/1.examples/3.assets-management/2.webpack-assets.md
  content/fr/1.examples/3.assets-management/index.md
  content/fr/1.examples/4.transitions/1.transitions.md
  content/fr/1.examples/5.seo/1.html-head.md
  content/fr/1.examples/5.seo/2.twitter-og.md
  content/fr/1.examples/5.seo/index.md
  content/fr/1.examples/6.loading/1.customize-nuxt-loading.md
  content/fr/1.examples/6.loading/2.customize-loading-indicator.md
  content/fr/1.examples/6.loading/3.custom-loading-component.md
  content/fr/1.examples/6.loading/index.md
  content/fr/1.examples/7.miscellaneous/1.layouts.md
  content/fr/1.examples/7.miscellaneous/2.lazy-loading-components.md
  content/fr/1.examples/7.miscellaneous/3.vuex-store.md
  content/fr/1.examples/7.miscellaneous/4.helpers.md
  content/fr/1.examples/7.miscellaneous/index.md
  content/fr/1.examples/8.middlewares/1.router.md
  content/fr/1.examples/8.middlewares/2.named.md
  content/fr/1.examples/8.middlewares/3.anonymous.md
  content/fr/1.examples/9.plugins/1.vue.md
  content/fr/1.examples/9.plugins/2.client-only.md
  content/fr/1.examples/9.plugins/3.external-packages.md
  content/fr/1.examples/9.plugins/4.custom.md
  content/fr/3.resources/video-courses.md
  content/fr/v3.md
Labels: documentation
