Repository nuxt/nuxtjs.org, pull requests merged in 2021-01, with the labels that each got.

#1093 docs(ja): translate pages-scrolltotop
  content/ja/guides/components-glossary/pages-scrolltotop.md
Labels: japanese

#1117 docs(ja): fix "main.css and main.css" to "main.scss to main.css"
  content/ja/guides/features/configuration.md
Labels: japanese

#1122 Fix(ja): parse errors
  content/ja/guides/directory-structure/middleware.md
  content/ja/guides/directory-structure/static.md
Labels: japanese

#1094 docs(ja): translate pages-watchquery
  content/ja/guides/components-glossary/pages-watchquery.md
Labels: japanese

#1107 docs(ja): Update docs
  content/ja/guides/concepts/nuxt-lifecycle.md
  content/ja/guides/concepts/static-site-generation.md
  content/ja/guides/configuration-glossary/configuration-build.md
  content/ja/guides/configuration-glossary/configuration-hooks.md
  content/ja/guides/configuration-glossary/configuration-loading-indicator.md
  content/ja/guides/configuration-glossary/configuration-render.md
  content/ja/guides/configuration-glossary/configuration-router.md
  content/ja/guides/configuration-glossary/configuration-server.md
  content/ja/guides/configuration-glossary/configuration-telemetry.md
  content/ja/guides/configuration-glossary/configuration-watchers.md
  content/ja/guides/directory-structure/assets.md
  content/ja/guides/directory-structure/content.md
  content/ja/guides/directory-structure/dist.md
  content/ja/guides/directory-structure/modules.md
  content/ja/guides/directory-structure/nuxt-config.md
  content/ja/guides/directory-structure/nuxt.md
  content/ja/guides/directory-structure/plugins.md
  content/ja/guides/features/data-fetching.md
  content/ja/guides/features/live-preview.md
  content/ja/guides/features/loading.md
  content/ja/guides/features/nuxt-components.md
  content/ja/guides/features/transitions.md
  content/ja/guides/get-started/installation.md
  content/ja/guides/internals-glossary/nuxt-render.md
Labels: japanese

#1096 docs(ja) fix directory-structure/static
  content/ja/guides/directory-structure/static.md
Labels: japanese

#1095 docs(ja): fix configuration-router
  content/ja/guides/configuration-glossary/configuration-router.md
Labels: japanese

#1111 docs(ja): Translate guides concepts SSR into Japanese
  content/ja/guides/concepts/server-side-rendering.md
Labels: japanese

#1108 docs(ja): translate pages-transition
  content/ja/guides/components-glossary/pages-transition.md
Labels: japanese

#1109 docs(ja): translate pages-validate
  content/ja/guides/components-glossary/pages-validate.md
Labels: japanese

#1127 docs(ja): translate directory-structure-assets
  content/ja/guides/directory-structure/assets.md
Labels: japanese

#1082 docs(tr): translate guides/components-glossary
  content/tr/guides/components-glossary/pages-fetch.md
  content/tr/guides/components-glossary/pages-head.md
  content/tr/guides/components-glossary/pages-key.md
  content/tr/guides/components-glossary/pages-layout.md
  content/tr/guides/components-glossary/pages-loading.md
  content/tr/guides/components-glossary/pages-middleware.md
  content/tr/guides/components-glossary/pages-scrolltotop.md
  content/tr/guides/components-glossary/pages-transition.md
  content/tr/guides/components-glossary/pages-validate.md
  content/tr/guides/components-glossary/pages-watchquery.md
Labels: turkish

#1089 docs(ja): install textlint for documentation in Japanese
  .github/workflows/textlint.yml
  .textlintrc
  content/ja/_archives/guide/development-tools.md
  content/ja/_archives/guide/index.md
  content/ja/_archives/guide/installation.md
  content/ja/_archives/guide/modules.md
  content/ja/_archives/guide/views.md
  content/ja/guides/concepts/views.md
  content/ja/guides/configuration-glossary/configuration-plugins.md
  content/ja/guides/configuration-glossary/configuration-rootdir.md
  content/ja/guides/directory-structure/assets.md
  content/ja/guides/directory-structure/content.md
  content/ja/guides/directory-structure/middleware.md
  content/ja/guides/features/configuration.md
  content/ja/guides/features/data-fetching.md
  content/ja/guides/features/deployment-targets.md
  content/ja/guides/features/file-system-routing.md
  content/ja/guides/features/live-preview.md
  content/ja/guides/features/transitions.md
  content/ja/guides/get-started/commands.md
  package.json
  yarn.lock
Labels: japanese

#1120 docs(ja): guides/concepts/static-site-generation.md
  content/ja/guides/concepts/static-site-generation.md
Labels: japanese

#1128 [Russian] Maxnvk/russian translation
  content/ru/guides/components-glossary/pages-fetch.md
  content/ru/guides/components-glossary/pages-head.md
  content/ru/guides/components-glossary/pages-key.md
  content/ru/guides/components-glossary/pages-layout.md
  content/ru/guides/components-glossary/pages-loading.md
Labels: russian, translations

#1056 Docs(id): translated configuration build and generate
  content/id/guides/configuration-glossary/configuration-build.md
  content/id/guides/configuration-glossary/configuration-generate.md
Labels: indonesia

#1158 [Russian] Concepts
  content/ru/guides/concepts/context-helpers.md
  content/ru/guides/concepts/nuxt-lifecycle.md
  content/ru/guides/concepts/server-side-rendering.md
  content/ru/guides/concepts/static-site-generation.md
  i18n/ru-RU.js
Labels: russian

#1081 docs(ja): translate directory-structure-dist
  content/ja/guides/directory-structure/dist.md
Labels: japanese

#1074 docs(ja): translate guides/directory-structure/store.md
  content/ja/guides/directory-structure/store.md
Labels: japanese

#1141 docs(tr): translate guides/concepts
  content/tr/guides/concepts/context-helpers.md
  content/tr/guides/concepts/nuxt-lifecycle.md
  content/tr/guides/concepts/server-side-rendering.md
  content/tr/guides/concepts/static-site-generation.md
  content/tr/guides/concepts/views.md
Labels: turkish

#1184 docs(zh) update translation：content/zh/guides/concepts
  content/zh/guides/concepts/context-helpers.md
  content/zh/guides/concepts/nuxt-lifecycle.md
  content/zh/guides/concepts/server-side-rendering.md
  content/zh/guides/concepts/static-site-generation.md
  content/zh/guides/concepts/views.md
Labels: chinese

#1139 docs(ja): guides/directory-structure/nuxt-config.md
  content/ja/guides/directory-structure/nuxt-config.md
Labels: japanese
