Repository nuxt/nuxtjs.org, pull requests merged in 2021-02, with the labels that each got.

#1012 [Spanish] docs(es): add examples book
  content/es/examples/custom-loading-component.md
  content/es/examples/customize-loading-indicator.md
  content/es/examples/customize-nuxt-loading.md
  content/es/examples/data-fetching-async-data.md
  content/es/examples/data-fetching-fetch-hook.md
  content/es/examples/hello-world.md
  content/es/examples/helpers.md
  content/es/examples/layouts.md
  content/es/examples/lazy-loading-components.md
  content/es/examples/middleware-anonymous.md
  content/es/examples/middleware-named.md
  content/es/examples/middleware-router.md
  content/es/examples/modules-axios.md
  content/es/examples/modules-internal.md
  content/es/examples/plugins-client-only.md
  content/es/examples/plugins-custom.md
  content/es/examples/plugins-external-packages.md
  content/es/examples/plugins-vue.md
  content/es/examples/pre-processors.md
  content/es/examples/routing-active-links-classes.md
  content/es/examples/routing-dynamic-pages.md
  content/es/examples/routing-nested-pages.md
  content/es/examples/seo-html-head.md
  content/es/examples/seo-twitter-og.md
  content/es/examples/transitions.md
  content/es/examples/vuex-store.md
  content/es/examples/webpack-assets.md
Labels: help wanted, spanish, translations

#1213 Docs(id): translated configuration alias and css
  content/id/guides/configuration-glossary/configuration-alias.md
  content/id/guides/configuration-glossary/configuration-css.md
Labels: indonesia

#1228 docs(ja): translate concepts/nuxt-lifecycle
  content/ja/guides/concepts/nuxt-lifecycle.md
Labels: japanese

#1230 docs(ja): translate internals-glossary/internals
  content/ja/guides/internals-glossary/internals.md
Labels: japanese

#1232 docs(ja): guides/directory-structure/nuxt.md
  content/ja/guides/directory-structure/nuxt.md
Labels: japanese

#1253 docs(id): translate configuration glossary to indonesian
  content/id/guides/configuration-glossary/configuration-builddir.md
  content/id/guides/configuration-glossary/configuration-dev.md
  content/id/guides/configuration-glossary/configuration-env.md
  content/id/guides/configuration-glossary/configuration-global-name.md
Labels: indonesia

#1227 docs(ja): translate concepts/context-helpers
  content/ja/guides/concepts/context-helpers.md
Labels: japanese

#1231 docs(ja): translate internals-glossary/internals-builder
  content/ja/guides/internals-glossary/internals-builder.md
Labels: japanese

#1229 docs(ja): translate internals-glossary/$nuxt
  content/ja/guides/internals-glossary/$nuxt.md
Labels: japanese

#1285 feat: add videos
  components/global/YouTubeLite.vue
  content/en/guides/get-started/commands.md
  content/en/guides/get-started/installation.md
  content/en/guides/get-started/routing.md
  nuxt.config.js
  package.json
  pages/docs/2.x/_book/_slug.vue
  plugins/youtube.client.js
  yarn.lock
Labels: enhancement

#1291 docs(id): translate untranslated thing in id-ID.js
  i18n/id-ID.js
Labels: indonesia

#1292 docs(id): translate configuration head and configuration hooks
  content/id/guides/configuration-glossary/configuration-head.md
  content/id/guides/configuration-glossary/configuration-hooks.md
Labels: indonesia

#1169 docs(id): translate modules.md into Indonesia
  content/id/guides/directory-structure/modules.md
Labels: indonesia

#1276 docs(id): finish translate directory structure to indonesia
  content/id/guides/directory-structure/nuxt-config.md
Labels: indonesia
